### ISSUE TITLE
What's the project for?

### ISSUE THREAD

**Issue by chengluyu** [SDUOJ/sduoj-web#1]
What's the purpose of this project?

**Comment by suxb201** [comment]
软工课的大作业

**Comment by GeneLiuXe** [comment]
We aim at creating an Online Judge System for SDU, which could not only implement basic functions of OJ, such as adding problems and holding contests, also provide a universal platform for students to improve their abilities of programming and for teachers to design more effective teaching methods in terms of programming.

**Comment by zhangt2333** [comment]
Aha, The conversation between the two above is funny !

**Comment by Menci** [comment]
Interesting.
